# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x10\x63om.example.grpc\"@\n\x0cloginRequest\x12\x15\n\rcustomer_name\x18\x01 \x01(\t\x12\x19\n\x11\x63ustomer_password\x18\x02 \x01(\t\"C\n\x0fregisterRequest\x12\x15\n\rcustomer_name\x18\x01 \x01(\t\x12\x19\n\x11\x63ustomer_password\x18\x02 \x01(\t\"#\n\x12validationResponce\x12\r\n\x05valid\x18\x01 \x01(\t2\xaa\x01\n\x04\x61uth\x12M\n\x05login\x12\x1e.com.example.grpc.loginRequest\x1a$.com.example.grpc.validationResponce\x12S\n\x08register\x12!.com.example.grpc.registerRequest\x1a$.com.example.grpc.validationResponceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_LOGINREQUEST']._serialized_start=32
  _globals['_LOGINREQUEST']._serialized_end=96
  _globals['_REGISTERREQUEST']._serialized_start=98
  _globals['_REGISTERREQUEST']._serialized_end=165
  _globals['_VALIDATIONRESPONCE']._serialized_start=167
  _globals['_VALIDATIONRESPONCE']._serialized_end=202
  _globals['_AUTH']._serialized_start=205
  _globals['_AUTH']._serialized_end=375
# @@protoc_insertion_point(module_scope)
